-- Lincies House: email OTP + phone collection + one active browser session + Zelle requests.
-- Run this once in Supabase SQL Editor before deploying these features.

alter table public.students
  add column if not exists phone text,
  add column if not exists active_session_token text,
  add column if not exists active_session_updated_at timestamptz;

create index if not exists students_phone_idx on public.students (phone);

update public.students
set phone = nullif(trim(phone), '')
where phone is not null;

create table if not exists public.zelle_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null,
  phone text not null,
  zelle_name text not null,
  note text,
  status text not null default 'pending',
  approved_at timestamptz
);

create index if not exists zelle_requests_status_created_idx
  on public.zelle_requests (status, created_at desc);

create index if not exists zelle_requests_email_idx
  on public.zelle_requests (lower(email));
