"use client";

import { useEffect } from "react";
import { courseChapters, totalCoreLessons } from "./courseData";
import "./globals.css";

export default function Page() {
  useEffect(() => {
    const buttons = document.querySelectorAll<HTMLButtonElement>(".qa button");
    const handlers: Array<() => void> = [];
    buttons.forEach((btn) => {
      const handler = () => btn.parentElement?.classList.toggle("open");
      btn.addEventListener("click", handler);
      handlers.push(() => btn.removeEventListener("click", handler));
    });
    return () => handlers.forEach((remove) => remove());
  }, []);

  return (
    <>
<div className="page">
<nav className="nav"><a className="logo" href="#top" aria-label="Lincies House home"><img className="script-logo" src="/assets/lincies-house-logo-transparent.png" alt="Lincies House logo" /></a><div className="navlinks"><a href="#course">Course</a><a href="/learn">Vào học</a><a href="#about">About Linh</a><a href="#toolkit">Toolkit</a><a href="#faq">FAQ</a></div><a className="cta" href="/learn">Student Login</a></nav>
<header className="hero" id="top"><div><div className="eyebrow"><span className="dot"></span> Khóa học Airbnb thực chiến • Vietnamese + English</div><h1>Airbnb thực chiến, <span className="highlight">từng bước tạo lợi nhuận.</span></h1><p className="lead">Từ chọn căn phù hợp, chuẩn bị nhà, tạo listing, đặt giá, nhận booking, chăm sóc guest đến xử lý vận hành — Lincies House hướng dẫn anh chị từng bước để bắt đầu và vận hành Airbnb có hệ thống.</p><div className="actions"><a className="btn primary" href="#pricing">Bắt đầu học cùng Linh →</a><a className="btn secondary" href="#course">Xem nội dung khóa học</a></div><div className="stats"><div className="stat"><b>{totalCoreLessons}</b><span>bài học chính đã gắn</span></div><div className="stat"><b>2</b><span>ngôn ngữ Việt + English</span></div><div className="stat"><b>7+</b><span>năm Superhost mindset</span></div></div></div><div className="visual"><div className="photo-card"></div><div className="mini"><b>Bonus</b><small>Update Library khi có nội dung quan trọng/phù hợp</small></div><div className="teacher-card"><div className="avatar"></div><h3>Learn with Linh</h3><p>Bắt đầu từ spare rooms năm 2019, sau đó host/co-host gần 30 listings tại LA, Dallas & Florida.</p></div></div></header>
<section className="section"><div className="section-title"><div><div className="kicker">Who this is for</div><h2>Bắt đầu đúng — hoặc vận hành bài bản hơn.</h2></div><p>Khóa học dành cho anh chị/các bạn muốn học Airbnb như một business thật sự, không phải chỉ xem vài video rời rạc rồi tự đoán.</p></div><div className="audience-grid"><div className="tile"><div className="icon">🏡</div><h3>Người mới bắt đầu</h3><p>Chưa biết nên làm gì trước, cần lộ trình rõ ràng từ nền tảng đến listing đầu tiên.</p></div><div className="tile"><div className="icon">🛏️</div><h3>Có nhà/phòng trống</h3><p>Muốn khai thác property đang có nhưng cần hiểu setup, rules, pricing và guest expectations.</p></div><div className="tile"><div className="icon">📈</div><h3>Đang có listing</h3><p>Muốn tối ưu listing, review, cleaner và operations để vận hành chuyên nghiệp hơn.</p></div><div className="tile"><div className="icon">🤝</div><h3>Muốn co-host</h3><p>Muốn hiểu cách hỗ trợ chủ nhà, giao tiếp với guest và quản lý vận hành hàng ngày.</p></div></div></section>
<section className="section story" id="about"><div className="story-photo"></div><div className="story-copy"><h2>Từ spare rooms trong nhà đến gần 30 listings ở nhiều thị trường.</h2><p>Linh bắt đầu Airbnb từ năm 2019 với phòng trống trong chính ngôi nhà của mình. Từ những bước nhỏ đó, Linh mở rộng sang rented homes, mua và remodel nhà cùng chồng, rồi host/co-host tại LA, Dallas và Florida.</p><p>Những bài học trong Lincies House đến từ tình huống thật: guest hỏi nhiều, cleaner trễ, pricing chưa đúng, review cần cải thiện, và những chi tiết nhỏ quyết định trải nghiệm của guest.</p><div className="story-points"><div className="point"><b>2019</b><span>bắt đầu Airbnb</span></div><div className="point"><b>~30</b><span>listings đã host/co-host</span></div><div className="point"><b>3</b><span>markets: LA, Dallas, Florida</span></div></div></div></section>
<section className="section" id="course" style={{ scrollMarginTop: "160px" }}><div className="section-title"><div><div className="kicker">Curriculum</div><h2>Lộ trình từ mindset đến vận hành.</h2></div><p>7 chương chính với {totalCoreLessons} video đã gắn Mux, giúp anh chị đi từ câu hỏi “nên bắt đầu thế nào?” đến cách vận hành listing bài bản.</p></div><div className="modules"><div className="module"><div className="num">01</div><h3>Airbnb như business</h3><p>Hiểu cơ hội, rủi ro, guest, reviews, chi phí và trách nhiệm thật sự của host.</p></div><div className="module"><div className="num">02</div><h3>Chọn mô hình</h3><p>Phòng trống, nhà riêng, thuê nhà, mua nhà hoặc co-host — hiểu hướng nào phù hợp.</p></div><div className="module"><div className="num">03</div><h3>Chuẩn bị property</h3><p>Amenities, rules, supplies, safety, local regulations và guest-ready checklist.</p></div><div className="module"><div className="num">04</div><h3>Setup listing</h3><p>Title, description, photos, house rules và expectations để guest hiểu đúng.</p></div><div className="module"><div className="num">05</div><h3>Pricing & calendar</h3><p>Base price, demand, minimum nights, discounts, seasonality và booking settings.</p></div><div className="module"><div className="num">06</div><h3>Operations</h3><p>Cleaner checklist, guest messages, check-in/check-out và maintenance flow.</p></div><div className="module"><div className="num">07</div><h3>Review & growth</h3><p>Cải thiện review, tối ưu listing theo thời gian, co-host và tư duy dài hạn.</p></div></div><div className="curriculum-panel"><div className="curriculum-head"><div><div className="kicker">Course video library</div><h3>{totalCoreLessons} bài học chính đã được chuẩn bị</h3></div><span>Protected by student login later</span></div><div className="chapter-list">{courseChapters.map((chapter) => (<div className="chapter-card" key={chapter.chapter}><div className="chapter-top"><div><span>Chương {chapter.chapter}</span><h4>{chapter.title}</h4></div><b>{chapter.lessons.length} video</b></div><ul>{chapter.lessons.map((lesson) => (<li key={lesson.playbackId}><span>{lesson.lesson}</span><strong>{lesson.title}</strong></li>))}</ul></div>))}</div><p className="curriculum-note">Trang học viên có video player, danh sách bài và tiến độ học. Phần login/thanh toán sẽ được khóa bằng Supabase + Stripe ở bước tiếp theo.</p></div></section>
<section className="section"><div className="section-title"><div><div className="kicker">Real portfolio energy</div><h2>Học từ những căn nhà Linh đã setup, host và tối ưu thực tế.</h2></div><p>Dùng hình thật của chị để landing page có cảm giác high-trust, cá nhân và không giống template stock.</p></div><div className="portfolio"><div className="home-card"><div><b>Bright family stay</b><span>Listing clarity + amenities</span></div></div><div className="home-card"><div><b>Cozy city home</b><span>Pricing + guest experience</span></div></div><div className="home-card"><div><b>Vacation-ready setup</b><span>Cleaner + operations flow</span></div></div></div></section>
<section className="section" id="pricing"><div className="price-wrap"><div><div className="kicker">Enroll</div><h2>Một lần mua, học cả tiếng Việt và English.</h2><p className="lead">Khóa học Airbnb Lincies House được thiết kế để anh chị học theo tốc độ riêng, xem lại khi đang setup listing hoặc khi gặp tình huống vận hành thực tế.</p></div><div className="price-card"><div className="eyebrow"><span className="dot"></span> Lincies House Airbnb Course</div><div className="price">$497</div><div className="list"><div className="li"><div className="check">✓</div>{totalCoreLessons} bài học chính đã gắn, đi từng bước từ nền tảng đến vận hành</div><div className="li"><div className="check">✓</div>Video tiếng Việt + English version trong cùng một lần mua</div><div className="li"><div className="check">✓</div>Airbnb Starter Toolkit: checklist, templates và tài liệu áp dụng</div><div className="li"><div className="check">✓</div>Lifetime access + Bonus Update Library khi có cập nhật quan trọng/phù hợp</div></div><a className="btn primary" href="/learn">Vào trang học thử →</a><p className="disclaimer">Không cam kết lợi nhuận. Airbnb là business thật sự và kết quả phụ thuộc vào location, property, chi phí, luật địa phương, pricing, reviews và cách vận hành.</p></div></div></section>
<section className="section" id="toolkit"><div className="section-title"><div><div className="kicker">Toolkit</div><h2>Không chỉ xem video — còn có tài liệu để làm theo.</h2></div><p>Toolkit giúp anh chị biến bài học thành checklist cụ thể trong lúc chuẩn bị và vận hành listing.</p></div><div className="toolkit"><div className="pill-card">Airbnb Setup Checklist</div><div className="pill-card">Cleaner Checklist</div><div className="pill-card">Guest Message Templates</div><div className="pill-card">Supplies & Operations Flow</div></div></section>
<section className="section" id="faq"><div className="section-title"><div><div className="kicker">FAQ</div><h2>Câu hỏi thường gặp trước khi đăng ký.</h2></div><p>FAQ giúp tăng SEO, giảm hesitation và trả lời các câu hỏi mua hàng quan trọng.</p></div><div className="faq"><div className="qa open"><button>Người mới hoàn toàn có học được không? <span>+</span></button><p>Có. Khóa học đi từ nền tảng, giúp anh chị hiểu Airbnb hoạt động thế nào trước khi setup listing.</p></div><div className="qa"><button>Có cần sở hữu nhà mới học được không? <span>+</span></button><p>Không nhất thiết. Có thể bắt đầu từ phòng trống, property đang có, thuê/mua nếu phù hợp hoặc co-host.</p></div><div className="qa"><button>Khóa học có update không? <span>+</span></button><p>Có Bonus Update Library khi có nội dung quan trọng và phù hợp, nhưng không hứa cập nhật mọi thay đổi ngay lập tức.</p></div><div className="qa"><button>Học xong có đảm bảo có lời không? <span>+</span></button><p>Không. Khóa học cung cấp kiến thức, hệ thống và checklist; kết quả phụ thuộc thị trường và cách vận hành.</p></div></div></section>
<footer className="footer"><h2>Ready to host with more confidence?</h2><p>Bắt đầu học Airbnb cùng Lincies House — thực chiến, rõ ràng, có hệ thống, và được xây dựng từ kinh nghiệm hosting thật.</p><a className="btn primary" style={{background:"#fff",color:"#17231d"}} href="#pricing">Bắt đầu học cùng Linh</a></footer>
</div>
    </>
  );
}
